import { Header, Footer } from "../page";

export default function CorporateSocialResponsibilityPage() {
  return (
    <>
      <Header />
      <div className="min-h-screen bg-[#FDFBF7] py-20 px-6 md:px-24 pt-32">
      <div className="max-w-4xl mx-auto">
        <h1 className="font-serif text-5xl mb-8">Corporate Social Responsibility Policy</h1>
        <div className="prose prose-lg max-w-none text-gray-800 space-y-6">
          <h2 className="font-bold text-2xl mt-8 mb-4">I. Minta Fresh’s philosophy and Vision</h2>
          <p className="mb-4">“Minta Fresh” is a Brand of Minta Club Private Limited (“Company”) is a responsible corporate, which strives for the overall betterment of the society at large. To this end, the Company seeks to undertake Corporate Social Responsibility (“CSR”) activities, which extend beyond the ambit of the business and focuses on human, environmental and social assets, with a special focus on addressing hunger, malnutrition, education and health. II. Objectives and Scope of the CSR Policy The CSR Policy lays down guidelines for the Company to undertake CSR activities, which are directed towards positively contributing to society through various sustainable and social welfare initiatives. The CSR Policy of the Company shall be governed by the various provisions of the Companies Act, 2013 (the “Act”), Companies (CSR Policy) Rules, 2014 (“CSR Rules”) and any other rules made thereunder, or that may apply from time to time.</p>
          <h2 className="font-bold text-2xl mt-8 mb-4">The Company proposes to undertake the CSR activities in the following areas</h2>
          <ul className="list-disc pl-6 space-y-2 mt-4 mb-4">
            <li>Eradicating hunger, poverty and malnutrition, promoting health care including preventive health care and sanitation including contribution to the Swachh Bharat Kosh set-up by the Central Government for the promotion of sanitation and making available safe drinking water;</li>
            <li>Promoting education, including special education and employment enhancing vocation skills especially among children, women, elderly and the differently abled and livelihood enhancement projects;</li>
            <li>Promoting gender equality, empowering women, operate or manage day care centres and such other facilities for senior citizens and measures for reducing inequalities faced by socially and economically backward groups;</li>
            <li>Ensuring environmental sustainability, ecological balance, protection of flora and fauna, animal welfare, agroforestry, conservation of natural resources;</li>
            <li>Contribution to the Prime Minister&apos;s National Relief Fund (PMNRF) or any other fund set up by the Central Government for socio economic development and relief and welfare of the schedule caste, tribes, other backward classes, minorities and women;</li>
            <li>Any other activity as specified under the Act, as amended from time to time. For the purpose of the CSR Policy, the CSR activities shall exclude activities undertaken in pursuance of the normal course of business of the Company. III. Implementation of the CSR Activities Pursuant to Section 135 of the Act, the Board of Directors of the Company (“Board”) has constituted a CSR committee, The CSR Committee and the Board are responsible for ensuring that the Company undertakes CSR activities in accordance with applicable law. The following framework will be adopted by the Company as and when it becomes legally obligated to</li>
          </ul>
          <h2 className="font-bold text-2xl mt-8 mb-4">undertake CSR activities as per the provisions of the Act</h2>
          <h2 className="font-bold text-2xl mt-8 mb-4">Responsibilities of the CSR Committee</h2>
          <p className="mb-4">The CSR Committee shall hold one meeting in every financial year, and if it deems necessary, may hold</p>
          <h2 className="font-bold text-2xl mt-8 mb-4">additional meetings (“CSR Meetings”) for the following matters</h2>
          <ul className="list-disc pl-6 space-y-2 mt-4 mb-4">
            <li>Monitor the implementation of the CSR activities undertaken by the Company.</li>
            <li>Prepare a status update in respect of each CSR activity.</li>
            <li>Deliberate upon and identify new CSR activities that the Company may undertake in that financial year.</li>
            <li>Include the details of CSR activities undertaken by the Company during the financial year in the Company’s annual report, as required under Section 134 of the Act.</li>
            <li>Discuss any matter in relation to the CSR activities of the Company, that the CSR Committee may choose to discuss. Monitoring of CSR activities The CSR Committee shall prepare a transparent monitoring mechanism for ensuring the implementation of the CSR activities proposed to be undertaken by the Company. Further, the CSR Committee shall provide the Board with a quarterly status update on the CSR expenditure. New CSR Activities The CSR Committee is tasked with identifying new social welfare initiatives that the Company can undertake as CSR activities under the CSR Policy. To this end, the CSR Committee shall explore the feasibility of various initiatives, and evaluate these initiatives in view of the objectives and scope of the CSR Policy and update the same in the policy, if required. Upon identifying a suitable social welfare initiative, the CSR Committee shall formulate a detailed plan, which specifies, inter alia, the end-goal of the initiative; expected expenditure; the time expected to be spent by the employees of the Company, if any; the modus operandi; timelines for various phases of the initiative; tie- ups or arrangements with third party entities, if any; and any other material factor that the CSR Committee may deem fit to be included (“CSR Plan”). The CSR Committee shall place the CSR Plan before the Board, for the Board’s approval. The Board reserves the right to make suitable modifications to the CSR Plan. The Company shall execute the CSR Plan in line with the modifications suggested by the Board. Revisions to the CSR Policy The CSR Committee shall review and recommend revisions to the CSR Policy, at least once a year and additionally whenever it deems fit, and place before the Board the CSR Policy containing such draft revisions for the Board’s approval. Any revisions to the CSR Policy shall be finalized only pursuant to the Board’s approval; notwithstanding the revisions suggested by the CSR Committee, the CSR Policy shall be amended in the form and manner as approved by the Board. External Assistance The CSR Committee reserves the right to obtain professional advice from external sources (such as expert agencies, NGOs, governmental authorities, etc.) for the purpose of carrying out the CSR activities (“Third</li>
          </ul>
          <p className="mb-4">Parties”). Where the Company engages Third Parties, the CSR Committee shall constitute a robust monitoring and implementation mechanism, to ensure that the funds and other resources of the Company are being used in an equitable and commercially judicious manner. In the event the Third Party so engaged requires access to the Company’s internal records, the same shall be shared on a need-to-know basis and only after the CSR Committee has passed a unanimous resolution, authorizing the same and recording its reasons in writing. IV. CSR Expenditure The Board shall ensure that the Company spends, in every financial year, a minimum of 2% of the average net profits of the Company made during the three immediately preceding financial years, on the CSR activities of the Company. All expenditure towards the CSR activities shall be diligently documented and maintained for at least 5 (five) years. Any surplus generated out of the CSR activities of the Company shall not form part of the business profits of the Company. V. Publication The CSR Policy shall be displayed on the Company’s website, available here www.mintafresh.com and link of the same will also be included in the Directors’ Report for every financial year.</p>
        </div>
      </div>
      </div>
      <Footer />
    </>
  );
}
